from .auth import InvalidTokenException, PermissionDeniedException
from .author import (
    AuthorAvatarAlreadyExists,
    AuthorAvatarDoesNotExist,
    AuthorSocialNetworkExistsException,
    RestrictedAuthorDeleting,
)
from .base import (
    BadRequestException,
    BaseHTTPException,
    BaseWebSocketException,
    DBConnectionException,
    ForeignKeyViolationException,
    ObjectExistsException,
    ObjectNotFoundException,
)
from .builder import ClusterBuilderException
from .cloudflare import (
    CloudflareARecordCreationException,
    CloudflareNoAccountException,
    CloudflareZoneCreationFailedException,
    CloudFlareZoneNotFoundException,
)
from .cluster import (
    ClusterAlreadyGeneratedException,
    ClusterIsGeneratingException,
    ClusterIsNotAllowToBuildException,
    ClusterIsNotAllowToGenerateException,
    ClusterIsNotAllowToUpdateException,
    ClusterPagesGenerationException,
    ClusterPagesGenerationFailedException,
    ClusterPageTopicsUpdateException,
    ClusterPageUpdateException,
    ClusterPageVersionDowngradeException,
    ClusterPageVersionUpgradeException,
    ClusterSettingUpdateException,
    ClusterStructureCreateError,
    ClusterVersionDowngradeException,
    ClusterVersionUpgradeException,
    ClusterWithoutPagesException,
    GenerateUndefinedErrorException,
    IndustryNotFoundException,
    InvalidKeywordException,
    MindmapFileUploadException,
    MindmapFileValidationException,
    MindmapPageCountMismatchException,
    NotEnoughBalanceForGeneration,
    ScreenshotCreatorException,
)
from .domain import DomainDNSCheckerServiceUnavailable, DomainNotAvailable, DomainsNotAvailable
from .integration import (
    IntegrationWPAlreadyExistsException,
    IntegrationWPConnectionException,
    IntegrationWPDomainNotFoundException,
    IntegrationWPInvalidAPIKeyException,
    IntegrationWPStillInProgressException,
    IntegrationWPWrongPluginUrl,
)
from .ovh import OVHFailedFetchFileException, OVHMaxRetryException
from .payment import NotEnoughBalanceForSpend
from .pbn import (
    MoneysiteIsProcessingException,
    PBNBuildingException,
    PbnDomainsCheckException,
    PBNExtraPageAlreadyGeneratedException,
    PBNExtraPageAuthorIsNotDefined,
    PBNExtraPageGenerationException,
    PBNExtraPageIsNotAllowToGenerateException,
    PBNExtraPageTitleException,
    PBNIsRefreshingException,
    PBNNotEnoughBalanceForGeneration,
    PBNPageTemplateException,
    PBNRefreshException,
)

__all__ = (
    "AuthorAvatarAlreadyExists",
    "AuthorAvatarDoesNotExist",
    "AuthorSocialNetworkExistsException",
    "BadRequestException",
    "BaseHTTPException",
    "BaseWebSocketException",
    "CloudFlareZoneNotFoundException",
    "CloudflareNoAccountException",
    "CloudflareZoneCreationFailedException",
    "ClusterAlreadyGeneratedException",
    "ClusterBuilderException",
    "ClusterIsGeneratingException",
    "ClusterIsNotAllowToBuildException",
    "ClusterIsNotAllowToGenerateException",
    "ClusterIsNotAllowToUpdateException",
    "ClusterPageTopicsUpdateException",
    "ClusterPageUpdateException",
    "ClusterPageVersionDowngradeException",
    "ClusterPageVersionUpgradeException",
    "ClusterPagesGenerationException",
    "ClusterPagesGenerationFailedException",
    "ClusterSettingUpdateException",
    "ClusterStructureCreateError",
    "ClusterVersionDowngradeException",
    "ClusterVersionUpgradeException",
    "ClusterWithoutPagesException",
    "DBConnectionException",
    "DomainDNSCheckerServiceUnavailable",
    "DomainNotAvailable",
    "DomainsNotAvailable",
    "ForeignKeyViolationException",
    "GenerateUndefinedErrorException",
    "IndustryNotFoundException",
    "IntegrationWPAlreadyExistsException",
    "IntegrationWPConnectionException",
    "IntegrationWPDomainNotFoundException",
    "IntegrationWPInvalidAPIKeyException",
    "IntegrationWPStillInProgressException",
    "IntegrationWPWrongPluginUrl",
    "InvalidKeywordException",
    "InvalidTokenException",
    "MindmapFileUploadException",
    "MindmapFileValidationException",
    "MindmapPageCountMismatchException",
    "NotEnoughBalanceForGeneration",
    "OVHFailedFetchFileException",
    "OVHMaxRetryException",
    "ObjectExistsException",
    "ObjectNotFoundException",
    "PBNExtraPageAlreadyGeneratedException",
    "PBNExtraPageAuthorIsNotDefined",
    "PBNExtraPageGenerationException",
    "PBNExtraPageIsNotAllowToGenerateException",
    "PBNNotEnoughBalanceForGeneration",
    "PbnDomainsCheckException",
    "MoneysiteIsProcessingException",
    "PermissionDeniedException",
    "RestrictedAuthorDeleting",
    "ScreenshotCreatorException",
)
