REPLACEMENTS_FR: dict[str, str] = {
    # ---------- A) accroître → augmenter (irregular) ----------
    "accroître": "augmenter",
    "accroît": "augmente",
    "accroissent": "augmentent",
    "accroissais": "augmentais",
    "accroissait": "augmentait",
    "accroissaient": "augmentaient",
    "accroîtra": "augmentera",
    "accroîtront": "augmenteront",
    "accroissant": "augmentant",
    "accru": "augmenté",
    "accrus": "augmentés",
    "accrue": "augmentée",
    "accrues": "augmentées",
    # ---------- B) explorer → examiner (regular) --------------
    "explorer": "examiner",
    "explore": "examine",
    "explores": "examines",
    "explorons": "examinons",
    "explorez": "examinez",
    "explorent": "examinent",
    "explorais": "examinais",
    "explorait": "examinait",
    "explorions": "examinions",
    "exploriez": "examiniez",
    "exploraient": "examinaient",
    "explorerai": "examinerai",
    "exploreras": "examineras",
    "explorera": "examinera",
    "explorerons": "examinerons",
    "explorerrez": "examinerez",
    "exploreront": "examineront",
    "explorant": "examinant",
    "exploré": "examiné",
    "explorés": "examinés",
    "explorée": "examinée",
    "explorées": "examinées",
    # ---------- C) maximiser → optimiser (regular) ------------
    "maximiser": "optimiser",
    "maximise": "optimise",
    "maximises": "optimises",
    "maximisons": "optimisons",
    "maximisez": "optimisez",
    "maximisent": "optimisent",
    "maximisais": "optimisais",
    "maximisait": "optimisait",
    "maximisions": "optimisions",
    "maximisiez": "optimisiez",
    "maximisaient": "optimisaient",
    "maximiserai": "optimiserai",
    "maximiseras": "optimiseras",
    "maximisera": "optimisera",
    "maximiserons": "optimiserons",
    "maximiserez": "optimiserez",
    "maximiseront": "optimiseront",
    "maximisant": "optimisant",
    "maximisé": "optimisé",
    "maximisés": "optimisés",
    "maximisée": "optimisée",
    "maximisées": "optimisées",
    # ---------- D) plonger → approfondir (regular) ------------
    "plonger": "approfondir",
    "plonge": "approfondis",
    "plonges": "approfondis",
    "plongeons": "approfondissons",
    "plongez": "approfondissez",
    "plongent": "approfondissent",
    "plongeais": "approfondissais",
    "plongeait": "approfondissait",
    "plongions": "approfondissions",
    "plongiez": "approfondissiez",
    "plongeaient": "approfondissaient",
    "plongerai": "approfondirai",
    "plongeras": "approfondiras",
    "plongera": "approfondira",
    "plongerons": "approfondirons",
    "plongerez": "approfondirez",
    "plongeront": "approfondiront",
    "plongeant": "approfondissant",
    "plongé": "approfondi",
    "plongés": "approfondis",
    "plongée": "approfondie",
    "plongées": "approfondies",
    # ---------- E) naviguer → approfondir (regular) ------------
    "naviguer": "traverser",
    "navigue": "traverse",
    "navigues": "traverses",
    "naviguons": "traversons",
    "naviguez": "traversez",
    "naviguent": "traversent",
    "naviguais": "traversais",
    "naviguait": "traversait",
    "naviguions": "traversions",
    "naviguiez": "traversiez",
    "naviguaient": "traversaient",
    "naviguerai": "traverserai",
    "navigueras": "traverseras",
    "naviguera": "traversera",
    "naviguerons": "traverserons",
    "naviguerez": "traverserez",
    "navigueront": "traverseront",
    "naviguant": "traversant",
    "navigué": "traversé",
    "navigués": "traversés",
    "naviguée": "traversée",
    "naviguées": "traversées",
    # ---------- F) Adjectifs / noms fléchis -------------------
    "captivant": "passionnant",
    "captivante": "passionnante",
    "captivants": "passionnants",
    "captivantes": "passionnantes",
    "fascinant": "passionnant",
    "fascinante": "passionnante",
    "fascinants": "passionnants",
    "fascinantes": "passionnantes",
    "crucial": "fondamental",
    "cruciale": "fondamentale",
    "cruciaux": "fondamentaux",
    "cruciales": "fondamentales",
    "pertinent": "approprié",
    "pertinente": "appropriée",
    "pertinents": "appropriés",
    "pertinentes": "appropriées",
    "facteur": "paramètre",
    "facteurs": "paramètres",
    # ---------- G) Mots / phrases statiques -------------------
    "afin que": "pour que",
    "ainsi que": "et",
    "avant que": "avant",
    "bien que": "malgré",
    "booster": "stimuler",
    "cependant": "mais",
    "cosmos": "espace",
    "dès que": "aussitôt que",
    "de plus": "par ailleurs",
    "domaine fascinant": "secteur passionnant",
    "élément essentiel": "composante clé",
    "en conclusion": "pour résumer",
    "exploration": "étude",
    "il est essentiel": "il est primordial",
    "la perle rare": "la solution idéale",
    "les meilleures pratiques": "les pratiques recommandées",
    "le monde": "la planète",
    "lorsque": "au moment où",
    "l'univers": "l'espace",
    "l'univers captivant": "l'espace passionnant",
    "même si": "même en cas de",
    "néanmoins": "malgré tout",
    "nous allons explorer": "nous allons examiner",
    "parce que": "car",
    "pourtant": "malgré cela",
    "puis": "ensuite",
    "puisque": "étant donné que",
    "quand": "au moment où",
    "quoique": "malgré que",
    "rôle clé": "rôle majeur",
    "stratégie seo": "optimisation pour moteurs de recherche",
    "tandis que": "alors que",
    "ton pote": "ton ami",
    "toutefois": "malgré tout",
    "univers": "espace",
}


REPLACEMENTS_US: dict[str, str] = {
    # ---------- Verbs ----------
    "blend": "mix",
    "blends": "mixes",
    "blended": "mixed",
    "blending": "mixing",
    "dance": "move",
    "dances": "moves",
    "danced": "moved",
    "dancing": "moving",
    "delve into": "examine",
    "delves into": "examines",
    "delved into": "examined",
    "delving into": "examining",
    "discover": "find",
    "discovers": "finds",
    "discovered": "found",
    "discovering": "finding",
    "embrace": "accept",
    "embraces": "accepts",
    "embraced": "accepted",
    "embracing": "accepting",
    "empathize": "relate",
    "empathizes": "relates",
    "empathized": "related",
    "empathizing": "relating",
    "enhance": "improve",
    "enhances": "improves",
    "enhanced": "improved",
    "enhancing": "improving",
    "ensure": "make sure",
    "ensures": "makes sure",
    "ensured": "made sure",
    "ensuring": "making sure",
    "evolve": "change",
    "evolves": "changes",
    "evolved": "changed",
    "evolving": "changing",
    "harness": "use",
    "harnesses": "uses",
    "harnessed": "used",
    "harnessing": "using",
    "indulge": "treat",
    "indulges": "treats",
    "indulged": "treated",
    "indulging": "treating",
    "maximize": "increase",
    "maximizes": "increases",
    "maximized": "increased",
    "maximizing": "increasing",
    "navigate": "guide",
    "navigates": "guides",
    "navigated": "guided",
    "navigating": "guiding",
    "reverberate": "echo",
    "reverberates": "echoes",
    "reverberated": "echoed",
    "reverberating": "echoing",
    "stand out": "shine",
    "stands out": "shines",
    "stood out": "shone",
    "standing out": "shining",
    "take a dive into": "investigate",
    "takes a dive into": "investigates",
    "took a dive into": "investigated",
    "taking a dive into": "investigating",
    "uncover": "reveal",
    "uncovers": "reveals",
    "uncovered": "revealed",
    "uncovering": "revealing",
    "underscore": "highlight",
    "underscores": "highlights",
    "underscored": "highlighted",
    "underscoring": "highlighting",
    "unleash": "release",
    "unleashes": "releases",
    "unleashed": "released",
    "unleashing": "releasing",
    "unlock": "open",
    "unlocks": "opens",
    "unlocked": "opened",
    "unlocking": "opening",
    "unveil": "reveal",
    "unveils": "reveals",
    "unveiled": "revealed",
    "unveiling": "revealing",
    # ---------- Nouns ----------
    "crucible": "test",
    "crucibles": "tests",
    "journey": "trip",
    "journeys": "trips",
    "labyrinth": "maze",
    "labyrinths": "mazes",
    "landscape": "scene",
    "landscapes": "scenes",
    "realm": "domain",
    "realms": "domains",
    "soul": "spirit",
    "souls": "spirits",
    "symphony": "harmony",
    "symphonies": "harmonies",
    "testament": "proof",
    "testaments": "proofs",
    # ---------- Adjectives / participles ----------
    "balanced": "even",
    "bustling": "lively",
    "compelling": "convincing",
    "complex and nuanced": "complex",
    "daunting": "challenging",
    "gossamer": "delicate",
    "indelible": "lasting",
    "labyrinthine": "complex",
    "metamorphosis": "change",
    "nestled": "situated",
    "nuanced": "subtle",
    "pesky": "annoying",
    "plethora": "abundance",
    "profound": "deep",
    "robust": "strong",
    "seamless": "smooth",
    "whimsical": "playful",
    # ---------- Linkers / adverbs / multi-word phrases ----------
    "alternatively": "or",
    "although": "though",
    "arguably": "perhaps",
    "as a result": "so",
    "as previously mentioned": "earlier",
    "as well as": "and",
    "because": "since",
    "consequently": "so",
    "constant reminder": "daily reminder",
    "despite": "even with",
    "due to": "on account of",
    "essential": "key",
    "essentially": "basically",
    "even if": "even when",
    "even though": "though",
    "furthermore": "also",
    "game changer": "breakthrough",
    "generally": "usually",
    "given that": "since",
    "however": "but",
    "importantly": "significantly",
    "indeed": "truly",
    "in addition": "also",
    "in conclusion": "to sum up",
    "in contrast": "conversely",
    "in order to": "to",
    "in summary": "to sum up",
    "in the context of": "regarding",
    "in the world of": "in",
    "it depends on": "depends on",
    "it is important to consider": "consider",
    "it is important to note": "note",
    "it is possible that": "perhaps",
    "it is worth noting that": "note",
    "look no further": "choose",
    "moreover": "also",
    "nonetheless": "still",
    "notably": "especially",
    "on the other hand": "conversely",
    "out of the box": "creative",
    "promptly": "quickly",
    "seamlessly": "smoothly",
    "similarly": "likewise",
    "specifically": "especially",
    "subsequently": "later",
    "that being said": "having said that",
    "therefore": "so",
    "there are several": "several",
    "this is not an exhaustive list": "this list is not complete",
    "thus": "so",
    "ultimately": "finally",
    "unique blend": "distinct mix",
    "unless": "except if",
    "vital": "very important",
    "sounds unheard": "hidden sounds",
    "sights unseen": "hidden sights",
}
