from enum import IntEnum, StrEnum


class BaseStrEnum(StrEnum):
    @classmethod
    def list(cls, part: int | None = None) -> list["BaseStrEnum"]:
        return list(cls.__members__.values())[:part]


class ExecutionMode(StrEnum):
    TEST = "test"
    PRODUCTION = "production"


class ProjectStage(StrEnum):
    LOCAL = "local"
    DEVELOPMENT = "development"
    PRODUCTION = "production"
    STAGING = "staging"


class StorageBackend(BaseStrEnum):
    LOCAL = "local"
    S3 = "s3"


class AppType(BaseStrEnum):
    LANDING = "landing"
    DESKTOP = "desktop"


class SpreadSheetFileExtension(BaseStrEnum):
    """Spreadsheet file extensions."""

    XLSX = "XLSX"
    XLS = "XLX"
    CSV = "CSV"


class ExceptionAlias(BaseStrEnum):
    UndefinedError = "undefined_error"

    # Author
    AuthorAvatarAlreadyExists = "author_avatar_already_exists"
    AuthorAvatarDoesNotExist = "author_avatar_does_not_exist"
    AuthorNotSet = "author_not_set"
    AuthorSocialNetworkExists = "author_social_network_exists"
    RestrictedAuthorDeleting = "restricted_author_deleting"

    # CloudFlare

    CloudflareNoAccount = "cloudflare_no_account"
    CloudFlareNoAvailableZone = "cloudflare_no_available_zone"
    CloudFlareZoneCreationFailed = "cloudflare_zone_creation_failed"
    CloudFlareARecordCreationFailed = "cloudflare_a_record_creation_failed"

    # Cluster
    ClusterAccessDenied = "cluster_access_denied"
    ClusterAlreadyGenerated = "cluster_already_generated"
    ClusterCreationFailed = "cluster_creation_failed"
    ClusterDoesNotExist = "cluster_does_not_exist"
    ClusterGenerateSuccess = "cluster_generate_success"
    ClusterIsGenerating = "cluster_is_generating"
    ClusterIsNotAllowToBuild = "cluster_is_not_allow_to_build"
    ClusterIsNotAllowToGenerate = "cluster_is_not_allow_to_generate"
    ClusterIsNotAllowToUpdate = "cluster_is_not_allow_to_update"
    ClusterPageIsNotAllowToUpdate = "cluster_page_is_not_allow_to_update"
    ClusterPageVersionDowngradeIsNotAllowed = "cluster_page_version_is_not_allowed_to_downgrade"
    ClusterPageVersionUpgradeIsNotAllowed = "cluster_page_version_is_not_allowed_to_upgrade"
    ClusterPagesGeneratedEmpty = "cluster_pages_generated_empty"
    ClusterPagesGenerationFailed = "cluster_pages_generation_failed"
    ClusterSettingIsNotAllowToUpdate = "cluster_setting_is_not_allow_to_update"
    ClusterTopicsAreNotAllowedToUpdate = "cluster_topics_are_not_allowed_to_update"
    ClusterVersionDowngradeIsNotAllowed = "cluster_version_is_not_allowed_to_downgrade"
    ClusterVersionUpgradeIsNotAllowed = "cluster_version_is_not_allowed_to_upgrade"
    ClusterWithoutPages = "cluster_without_pages"
    FailToUploadToWordPress = "fail_to_upload_to_wordpress"
    IndustryNotFound = "industry_not_found"
    InvalidKeyword = "invalid_keyword"
    MindmapFileUploadFailed = "mindmap_file_upload_failed"
    MindmapPageCountMismatch = "mindmap_page_count_mismatch"
    NotEnoughBalanceForGeneration = "not_enough_balance_for_generation"
    ScreenshotCreator = "screenshot_creator"

    # Fingerprint
    FingerprintAlreadyExists = "fingerprint_already_exists"
    FingerprintAlreadyBounded = "fingerprint_already_bounded"

    # Comments
    CommentsIpLimitExceeded = "page_comment_limit_exceeded"
    CommentsPageLimitExceeded = "ip_comment_limit_exceeded"

    # CTR
    CTRAccessDenied = "ctr_access_denied"
    CTRInvalidPatterns = "ctr_invalid_patterns"
    CTRPatternUnableModify = "ctr_pattern_unable_to_modify"
    CTRUnknownEventType = "ctr_unknown_event_type"

    # Database
    DBObjectNotFound = "db_object_not_found"

    # Domain
    DomainCustomIsNotConfirmed = "domain_custom_is_not_confirmed"
    DomainDNSCheckerServiceUnavailable = "domain_dns_checker_service_unavailable"
    DomainNotAvailable = "domain_is_not_available"
    DomainsNotAvailable = "domains_are_not_available"
    DynadotApiRequestFailed = "dynadot_api_request_failed"

    # Deploy
    ServiceUnavailable = "service_unavailable_for_generating_or_building"

    # Integration WordPress
    WPAlreadyExists = "wp_integration_already_exists"
    WPBadConnection = "wp_bad_connection_to_plugin"
    WPDomainNotFound = "wp_domain_not_found"
    WPInvalidAPIKey = "wp_invalid_api_key"
    WPIsNotLatestVersion = "wp_is_not_latest_version"
    WPStillInProgress = "wp_integration_still_in_progress"
    WPWrongPluginUrl = "wp_wrong_plugin_url"

    # OTP
    InvalidOTP = "invalid_otp"
    OTPCodeSendingFailed = "otp_code_sending_failed"
    OTPActionNotDefined = "otp_action_not_defined"

    # Referral
    VoucherExpired = "voucher_expired"

    # User
    AuthorizationFailed = "authorization_failed"
    IncorrectPassword = "incorrect_password"
    PasswordsNotMatch = "passwords_not_match"
    SetReferralCodeTimeout = "set_referral_code_timeout"
    UserAlreadyExists = "user_already_exists"
    UserAlreadyHasReferralCode = "user_already_has_referral_code"
    UserDeactivated = "user_deactivated"
    UserNotFound = "user_not_found"

    # SpreadSheetFile
    UnsupportedSpreadSheetFileFormat = "unsupported_spread_sheet_file_format"

    # SMTP
    ObjectNotAuthenticated = "object_not_authenticated"
    MessageIsLarge = "message is too large"

    # General
    FailedFetchFile = "failed_fetch_file"
    InvalidToken = "invalid_token"
    PermissionDenied = "permission_denied"
    WorkerUnavailable = "worker_unavailable"

    # Payment
    NotEnoughBalanceForWithdraw = "not_enough_balance_for_withdraw"
    NotEnoughBalanceForSpend = "not_enough_balance_for_spend"
    StripePayload = "stripe_payload"
    StripeSignature = "stripe_signature"
    ValidatedCard = "validated_card"

    # Project
    ProjectClusterCreationFailed = "project_cluster_creation_failed"

    # MoneySite
    MoneysiteRequestError = "moneysite_request_error"
    MoneysiteProcessing = "moneysite_is_processing"

    # PBN
    PBNIsGenerating = "pbn_is_generating"
    PBNGenerationFailed = "pbn_generation_failed"
    PBNHomePageTemplateRenderError = "pbn_home_page_render_error"
    PBNPlanStructureRenderError = "pbn_plan_structure_render_error"
    PBNBuildError = "pbn_build_error"
    PBNIsRefreshing = "pbn_is_refreshing"
    PBNUnableToRefresh = "unable_to_refresh"
    PBNIsRedeploying = "pbn_is_redeploying"

    # PBN Extra page
    PBNExtraPageAlreadyGenerated = "pbn_extra_page_already_generated"
    PBNExtraPageIsNotAllowToBuild = "pbn_extra_page_is_not_allow_to_build"
    PBNExtraPageIsNotAllowToGenerate = "pbn_extra_page_is_not_allow_to_generate"
    PBNExtraPageIsGenerating = "pbn_extra_page_is_generating"
    PBNExtraPageGeneratedError = "pbn_extra_page_generate_error"
    PBNExtraPageAuthorIsNotDefined = "pbn extra_page_author_is_not_defined"

    # Project
    ClusterAlreadyAddedToProject = "cluster_already_added_to_project"
    ClusterNotAddedToProject = "cluster_not_added_to_project"

    # Provider Server
    ServerNotAvailable = "server_is_not_available"


class OrderDirection(BaseStrEnum):
    ASC = "asc"
    DESC = "desc"


class ObjectExtension(StrEnum):
    GIF = ".gif"
    JSON = ".json"
    MP3 = ".mp3"
    MP4 = ".mp4"
    SNAPSHOT = ".snst"
    WEBP = ".webp"
    ZIP = ".zip"


class LangCode(BaseStrEnum):
    US = "1000"
    FR = "1002"


class LanguageCode(BaseStrEnum):
    US = "EN"
    FR = "FR"


class CountryCode(BaseStrEnum):
    US = "1023191"
    FR = "9040871"


class GeoPaths(BaseStrEnum):
    US = "2048"
    FR = "20321"


class HttpMethodType(StrEnum):
    GET = "get"
    POST = "post"
    PUT = "put"
    DELETE = "delete"


class CountryNames(BaseStrEnum):
    AD = "Andorra"
    AE = "United Arab Emirates"
    AF = "Afghanistan"
    AG = "Antigua and Barbuda"
    AI = "Anguilla"
    AL = "Albania"
    AM = "Armenia"
    AO = "Angola"
    AQ = "Antarctica"
    AR = "Argentina"
    AS = ("American Samoa",)
    AT = "Austria"
    AU = "Australia"
    AW = "Aruba"
    AX = "Aland Islands"
    AZ = "Azerbaijan"
    BA = "Bosnia and Herzegovina"
    BB = "Barbados"
    BD = "Bangladesh"
    BE = "Belgium"
    BF = "Burkina Faso"
    BG = "Bulgaria"
    BH = "Bahrain"
    BI = "Burundi"
    BJ = "Benin"
    BL = "Saint Barthelemy"
    BM = "Bermuda"
    BN = "Brunei Darussalam"
    BO = "Bolivia"
    BQ = "Caribbean Netherlands"
    BR = "Brazil"
    BS = "Bahamas"
    BT = "Bhutan"
    BV = "Bouvet Island"
    BW = "Botswana"
    BY = "Belarus"
    BZ = "Belize"
    CA = "Canada"
    CC = "Cocos (Keeling) Islands"
    CD = "Democratic Republic of the Congo"
    CF = "Central African Republic"
    CG = "Congo"
    CH = "Switzerland"
    CI = "Cote d'Ivoire"
    CK = "Cook Islands"
    CL = "Chile"
    CM = "Cameroon"
    CN = "China"
    CO = "Colombia"
    CR = "Costa Rica"
    CU = "Cuba"
    CV = "Cabo Verde"
    CW = "Curacao"
    CX = "Christmas Island"
    CY = "Cyprus"
    CZ = "Czechia"
    DE = "Germany"
    DJ = "Djibouti"
    DK = "Denmark"
    DM = "Dominica"
    DO = "Dominican Republic"
    DZ = "Algeria"
    EC = "Ecuador"
    EE = "Estonia"
    EG = "Egypt"
    EH = "Western Sahara"
    ER = "Eritrea"
    ES = "Spain"
    ET = "Ethiopia"
    FI = "Finland"
    FJ = "Fiji"
    FK = "Falkland Islands"
    FM = "Micronesia"
    FO = "Faroe Islands"
    FR = "France"
    GA = "Gabon"
    GB = "United Kingdom"
    GD = "Grenada"
    GE = "Georgia"
    GF = "French Guiana"
    GG = "Guernsey"
    GH = "Ghana"
    GI = "Gibraltar"
    GL = "Greenland"
    GM = "Gambia"
    GN = "Guinea"
    GP = "Guadeloupe"
    GQ = "Equatorial Guinea"
    GR = "Greece"
    GS = "South Georgia and the South Sandwich Islands"
    GT = "Guatemala"
    GU = "Guam"
    GW = "Guinea-Bissau"
    GY = "Guyana"
    HK = "Hong Kong"
    HM = "Heard Island and McDonald Islands"
    HN = "Honduras"
    HR = "Croatia"
    HT = "Haiti"
    HU = "Hungary"
    ID = "Indonesia"
    IE = "Ireland"
    IL = "Israel"
    IM = "Isle of Man"
    IN = "India"
    IO = "British Indian Ocean Territory"
    IQ = "Iraq"
    IR = "Iran"
    IS = "Iceland"
    IT = "Italy"
    JE = "Jersey"
    JM = "Jamaica"
    JO = "Jordan"
    JP = "Japan"
    KE = "Kenya"
    KG = "Kyrgyzstan"
    KH = "Cambodia"
    KI = "Kiribati"
    KM = "Comoros"
    KN = "Saint Kitts and Nevis"
    KP = "North Korea"
    KR = "South Korea"
    KW = "Kuwait"
    KY = "Cayman Islands"
    KZ = "Kazakhstan"
    LA = "Laos"
    LB = "Lebanon"
    LC = "Saint Lucia"
    LI = "Liechtenstein"
    LK = "Sri Lanka"
    LR = "Liberia"
    LS = "Lesotho"
    LT = "Lithuania"
    LU = "Luxembourg"
    LV = "Latvia"
    LY = "Libya"
    MA = "Morocco"
    MC = "Monaco"
    MD = "Moldova"
    ME = "Montenegro"
    MF = "Saint Martin"
    MG = "Madagascar"
    MH = "Marshall Islands"
    MK = "North Macedonia"
    ML = "Mali"
    MM = "Myanmar"
    MN = "Mongolia"
    MO = "Macao"
    MP = "Northern Mariana Islands"
    MQ = "Martinique"
    MR = "Mauritania"
    MS = "Montserrat"
    MT = "Malta"
    MU = "Mauritius"
    MV = "Maldives"
    MW = "Malawi"
    MX = "Mexico"
    MY = "Malaysia"
    MZ = "Mozambique"
    NA = "Namibia"
    NC = "New Caledonia"
    NE = "Niger"
    NF = "Norfolk Island"
    NG = "Nigeria"
    NI = "Nicaragua"
    NL = "Netherlands"
    NO = "Norway"
    NP = "Nepal"
    NR = "Nauru"
    NU = "Niue"
    NZ = "New Zealand"
    OM = "Oman"
    PA = "Panama"
    PE = "Peru"
    PF = "French Polynesia"
    PG = "Papua New Guinea"
    PH = "Philippines"
    PK = "Pakistan"
    PL = "Poland"
    PM = "Saint Pierre and Miquelon"
    PN = "Pitcairn"
    PR = "Puerto Rico"
    PS = "Palestine, State of"
    PT = "Portugal"
    PW = "Palau"
    PY = "Paraguay"
    QA = "Qatar"
    RE = "Reunion"
    RO = "Romania"
    RS = "Serbia"
    RU = "Russian Federation"
    RW = "Rwanda"
    SA = "Saudi Arabia"
    SB = "Solomon Islands"
    SC = "Seychelles"
    SD = "Sudan"
    SE = "Sweden"
    SG = "Singapore"
    SH = "Saint Helena, Ascension and Tristan da Cunha"
    SI = "Slovenia"
    SJ = "Svalbard and Jan Mayen"
    SK = "Slovakia"
    SL = "Sierra Leone"
    SM = "San Marino"
    SN = "Senegal"
    SO = "Somalia"
    SR = "Suriname"
    SS = "South Sudan"
    ST = "Sao Tome and Principe"
    SV = "El Salvador"
    SX = "Sint Maarten"
    SY = "Syrian Arab Republic"
    SZ = "Eswatini"
    TC = "Turks and Caicos Islands"
    TD = "Chad"
    TF = "French Southern Territories"
    TG = "Togo"
    TH = "Thailand"
    TJ = "Tajikistan"
    TK = "Tokelau"
    TL = "Timor-Leste"
    TM = "Turkmenistan"
    TN = "Tunisia"
    TO = "Tonga"
    TR = "Turkey"
    TT = "Trinidad and Tobago"
    TV = "Tuvalu"
    TW = "Taiwan"
    TZ = "Tanzania"
    UA = "Ukraine"
    UG = "Uganda"
    UM = "United States Minor Outlying Islands"
    US = "United States"
    UY = "Uruguay"
    UZ = "Uzbekistan"
    VA = "Holy See"
    VC = "Saint Vincent and the Grenadines"
    VE = "Venezuela"
    VG = "Virgin Islands (British)"
    VI = "Virgin Islands (U.S.)"
    VN = "Viet Nam"
    VU = "Vanuatu"
    WF = "Wallis and Futuna"
    WS = "Samoa"
    YE = "Yemen"
    YT = "Mayotte"
    ZA = "South Africa"
    ZM = "Zambia"
    ZW = "Zimbabwe"


class Language(BaseStrEnum):
    US = "US"
    FR = "FR"

    @property
    def lang_code(self) -> str:
        return getattr(LangCode, self)

    @property
    def language_code(self) -> str:
        return getattr(LanguageCode, self)

    @property
    def country_code(self) -> str:
        return getattr(CountryCode, self)

    @property
    def country_name(self) -> str:
        return getattr(CountryNames, self)

    @property
    def geo_path(self) -> str:
        return getattr(GeoPaths, self)


class SocialNetworkType(BaseStrEnum):
    AMAZON = "AMAZON"
    FACEBOOK = "FACEBOOK"
    INSTAGRAM = "INSTAGRAM"
    LINKEDIN = "LINKEDIN"
    MEDIUM = "MEDIUM"
    REDDIT = "REDDIT"
    WEBSITE = "WEBSITE"
    X = "X"
    YOUTUBE = "YOUTUBE"


class Country(BaseStrEnum):
    AF = "AF"
    AL = "AL"
    DZ = "DZ"
    AS = "AS"
    AD = "AD"
    AO = "AO"
    AI = "AI"
    AQ = "AQ"
    AG = "AG"
    AR = "AR"
    AM = "AM"
    AW = "AW"
    AU = "AU"
    AT = "AT"
    AZ = "AZ"
    BS = "BS"
    BH = "BH"
    BD = "BD"
    BB = "BB"
    BY = "BY"
    BE = "BE"
    BZ = "BZ"
    BJ = "BJ"
    BM = "BM"
    BT = "BT"
    BO = "BO"
    BQ = "BQ"
    BA = "BA"
    BW = "BW"
    BV = "BV"
    BR = "BR"
    IO = "IO"
    BN = "BN"
    BG = "BG"
    BF = "BF"
    BI = "BI"
    CV = "CV"
    KH = "KH"
    CM = "CM"
    CA = "CA"
    KY = "KY"
    CF = "CF"
    TD = "TD"
    CL = "CL"
    CN = "CN"
    CX = "CX"
    CC = "CC"
    CO = "CO"
    KM = "KM"
    CD = "CD"
    CG = "CG"
    CK = "CK"
    CR = "CR"
    HR = "HR"
    CU = "CU"
    CW = "CW"
    CY = "CY"
    CZ = "CZ"
    CI = "CI"
    DK = "DK"
    DJ = "DJ"
    DM = "DM"
    DO = "DO"
    EC = "EC"
    EG = "EG"
    SV = "SV"
    GQ = "GQ"
    ER = "ER"
    EE = "EE"
    SZ = "SZ"
    ET = "ET"
    FK = "FK"
    FO = "FO"
    FJ = "FJ"
    FI = "FI"
    FR = "FR"
    GF = "GF"
    PF = "PF"
    TF = "TF"
    GA = "GA"
    GM = "GM"
    GE = "GE"
    DE = "DE"
    GH = "GH"
    GI = "GI"
    GR = "GR"
    GL = "GL"
    GD = "GD"
    GP = "GP"
    GU = "GU"
    GT = "GT"
    GG = "GG"
    GN = "GN"
    GW = "GW"
    GY = "GY"
    HT = "HT"
    HM = "HM"
    VA = "VA"
    HN = "HN"
    HK = "HK"
    HU = "HU"
    IS = "IS"
    IN = "IN"
    ID = "ID"
    IR = "IR"
    IQ = "IQ"
    IE = "IE"
    IM = "IM"
    IL = "IL"
    IT = "IT"
    JM = "JM"
    JP = "JP"
    JE = "JE"
    JO = "JO"
    KZ = "KZ"
    KE = "KE"
    KI = "KI"
    KP = "KP"
    KR = "KR"
    KW = "KW"
    KG = "KG"
    LA = "LA"
    LV = "LV"
    LB = "LB"
    LS = "LS"
    LR = "LR"
    LY = "LY"
    LI = "LI"
    LT = "LT"
    LU = "LU"
    MO = "MO"
    MG = "MG"
    MW = "MW"
    MY = "MY"
    MV = "MV"
    ML = "ML"
    MT = "MT"
    MH = "MH"
    MQ = "MQ"
    MR = "MR"
    MU = "MU"
    YT = "YT"
    MX = "MX"
    FM = "FM"
    MD = "MD"
    MC = "MC"
    MN = "MN"
    ME = "ME"
    MS = "MS"
    MA = "MA"
    MZ = "MZ"
    MM = "MM"
    NA = "NA"
    NR = "NR"
    NP = "NP"
    NL = "NL"
    NC = "NC"
    NZ = "NZ"
    NI = "NI"
    NE = "NE"
    NG = "NG"
    NU = "NU"
    NF = "NF"
    MP = "MP"
    NO = "NO"
    OM = "OM"
    PK = "PK"
    PW = "PW"
    PS = "PS"
    PA = "PA"
    PG = "PG"
    PY = "PY"
    PE = "PE"
    PH = "PH"
    PN = "PN"
    PL = "PL"
    PT = "PT"
    PR = "PR"
    QA = "QA"
    MK = "MK"
    RO = "RO"
    RU = "RU"
    RW = "RW"
    RE = "RE"
    BL = "BL"
    SH = "SH"
    KN = "KN"
    LC = "LC"
    MF = "MF"
    PM = "PM"
    VC = "VC"
    WS = "WS"
    SM = "SM"
    ST = "ST"
    SA = "SA"
    SN = "SN"
    RS = "RS"
    SC = "SC"
    SL = "SL"
    SG = "SG"
    SX = "SX"
    SK = "SK"
    SI = "SI"
    SB = "SB"
    SO = "SO"
    ZA = "ZA"
    GS = "GS"
    SS = "SS"
    ES = "ES"
    LK = "LK"
    SD = "SD"
    SR = "SR"
    SJ = "SJ"
    SE = "SE"
    CH = "CH"
    SY = "SY"
    TW = "TW"
    TJ = "TJ"
    TZ = "TZ"
    TH = "TH"
    TL = "TL"
    TG = "TG"
    TK = "TK"
    TO = "TO"
    TT = "TT"
    TN = "TN"
    TR = "TR"
    TM = "TM"
    TC = "TC"
    TV = "TV"
    UG = "UG"
    UA = "UA"
    AE = "AE"
    GB = "GB"
    UM = "UM"
    US = "US"
    UY = "UY"
    UZ = "UZ"
    VU = "VU"
    VE = "VE"
    VN = "VN"
    VG = "VG"
    VI = "VI"
    WF = "WF"
    EH = "EH"
    YE = "YE"
    ZM = "ZM"
    ZW = "ZW"
    AX = "AX"

    @property
    def country_name(self) -> str:
        return getattr(CountryNames, self)


class Day(IntEnum):
    MONDAY = 1
    TUESDAY = 2
    WEDNESDAY = 3
    THURSDAY = 4
    FRIDAY = 5
    SATURDAY = 6
    SUNDAY = 7
